name: ActionHealth
main: com.zeshanaslam.actionhealth.Main
version: 3.5.3
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI, WorldGuard, mcMMO, MythicMobs, LangUtils]
commands:
  Actionhealth:
    description: Actionhealth main commands.
